function menu_goto( menuform )
{
  // Generated by thesitewizard Navigation Menu Wizard 2.3.2
  // Visit http://www.thesitewizard.com/ to get your own
  // customized navigation menu FREE!
  var baseurl = 'http://library.Reynolds.edu' ;
  selecteditem = menuform.url.selectedIndex ;
  newurl = menuform.url.options[ selecteditem ].value ;
  if (newurl.length != 0) {
    location.href = baseurl + newurl ;
  }
}

document.writeln( '<form action="chgoto" method="get">' );
document.writeln( '<select name="url" onchange="menu_goto(this.form)">' );
document.writeln( '<option selected="selected" value="">--- Choose a Subject ---</option>' );
document.writeln( '<option value="/find/databases/subject.htm#argument">Arguments, Viewpoints &amp; Controversial Issues</option>' );
document.writeln( '<option value="/find/databases/subject.htm#arts">Arts &amp; Music</option>' );
document.writeln( '<option value="/find/databases/subject.htm#biography">Biographies</option>' );
document.writeln( '<option value="/find/databases/subject.htm#biology">Biology</option>' );
document.writeln( '<option value="/find/databases/subject.htm#bookreviews">Book Reviews</option>' );
document.writeln( '<option value="/find/databases/subject.htm#business">Business &amp; Economics</option>' );
document.writeln( '<option value="/find/databases/subject.htm#career">Career Development &amp; Jobs</option>' );
document.writeln( '<option value="/find/databases/subject.htm#chemistry">Chemistry &amp; Physics</option>' );
document.writeln( '<option value="/find/databases/subject.htm#computer">Computer Science &amp; Information Technology</option>' );
document.writeln( '<option value="/find/databases/subject.htm#conference">Conference Proceedings</option>' );
document.writeln( '<option value="/find/databases/subject.htm#culinary">Culinary Arts, Tourism &amp; Hospitality</option>' );
document.writeln( '<option value="/find/databases/subject.htm#education">Education</option>' );
document.writeln( '<option value="/find/databases/subject.htm#engineering">Engineering &amp; Materials Science</option>' );
document.writeln( '<option value="/find/databases/subject.htm#literature">English &amp; Literature</option>' );
document.writeln( '<option value="/find/databases/subject.htm#foreign">Foreign Language Databases</option>' );
document.writeln( '<option value="/find/databases/subject.htm#geography">Geography, Earth, &amp; Environmental Sciences</option>' );
document.writeln( '<option value="/find/databases/subject.htm#health">Health, Medicine &amp; Nursing</option>' );
document.writeln( '<option value="/find/databases/subject.htm#history">History</option>' );
document.writeln( '<option value="/find/databases/subject.htm#horticulture">Horticulture</option>' );
document.writeln( '<option value="/find/databases/subject.htm#law">Law &amp; Government</option>' );
document.writeln( '<option value="/find/databases/subject.htm#material">Materials Science</option>' );
document.writeln( '<option value="/find/databases/subject.htm#math">Mathematics</option>' );
document.writeln( '<option value="/find/databases/subject.htm#news">Newspapers</option>' );
document.writeln( '<option value="/find/databases/subject.htm#psych">Psychology</option>' );
document.writeln( '<option value="/find/databases/subject.htm#ref">Reference (almanacs, dictionaries, encyclopedias)</option>' );
document.writeln( '<option value="/find/databases/subject.htm#science">Science (General)</option>' );
document.writeln( '<option value="/find/databases/subject.htm#social">Social Sciences</option>' );
document.writeln( '<option value="/find/databases/subject.htm#statistics">Statistics</option>' );
document.writeln( '</select>' );
document.writeln( '</form>' );
