function menu_goto( menuform )
{
  // Generated by thesitewizard Navigation Menu Wizard 2.3.2
  // Visit http://www.thesitewizard.com/ to get your own
  // customized navigation menu FREE!
  var baseurl = 'http://libguides.Reynolds.edu/content.php?pid=271769' ;
  selecteditem = menuform.url.selectedIndex ;
  newurl = menuform.url.options[ selecteditem ].value ;
  if (newurl.length != 0) {
    location.href = baseurl + newurl ;
  }
}

document.writeln( '<form action="chgoto" method="get">' );
document.writeln( '<select name="url" onchange="menu_goto(this.form)">' );
document.writeln( '<option selected="selected" value="">--- Choose a Subject ---</option>' );
document.writeln( '<option value="&sid=2241236">Arguments, Viewpoints &amp; Controversial Issues</option>' );
document.writeln( '<option value="&sid=2241270">Arts &amp; Music</option>' );
document.writeln( '<option value="&sid=2241323">Biographies</option>' );
document.writeln( '<option value="&sid=2241388">Biology</option>' );
document.writeln( '<option value="&sid=2241389">Book Reviews</option>' );
document.writeln( '<option value="&sid=2241395">Business &amp; Economics</option>' );
document.writeln( '<option value="&sid=2582762">Career Development &amp; Jobs</option>' );
document.writeln( '<option value="&sid=2241417">Chemistry</option>' );
document.writeln( '<option value="&sid=2241420">Computer Science &amp; Information Technology</option>' );
document.writeln( '<option value="&sid=2241423">Culinary Arts, Tourism &amp; Hospitality</option>' );
document.writeln( '<option value="&sid=2241424">Education</option>' );
document.writeln( '<option value="&sid=2241426">Engineering &amp; Materials Science</option>' );
document.writeln( '<option value="&sid=2241430">English &amp; Literature</option>' );
document.writeln( '<option value="&sid=2241433">Foreign Language Databases</option>' );
document.writeln( '<option value="&sid=2299424">Geography, Earth, &amp; Environmental Sciences</option>' );
document.writeln( '<option value="&sid=2241437">Health, Medicine &amp; Nursing</option>' );
document.writeln( '<option value="&sid=2241444">History</option>' );
document.writeln( '<option value="&sid=2241445">Horticulture</option>' );
document.writeln( '<option value="&sid=2241447">Law &amp; Government</option>' );
document.writeln( '<option value="&sid=2241450">Mathematics</option>' );
document.writeln( '<option value="&sid=2241451">Newspapers</option>' );
document.writeln( '<option value="&sid=2241466">Philosophy &amp; Religion</option>' );
document.writeln( '<option value="&sid=2241468">Physics</option>' ); 
document.writeln( '<option value="&sid=2241471">Psychology</option>' );
document.writeln( '<option value="&sid=2241473">Reference (almanacs, dictionaries, encyclopedias)</option>' );
document.writeln( '<option value="&sid=2241477">Science (General)</option>' );
document.writeln( '<option value="&sid=2241480">Social Sciences</option>' );
document.writeln( '<option value="&sid=2241483">Statistics</option>' );
document.writeln( '</select>' );
document.writeln( '</form>' );
